using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using Telerik.Windows.Controls.Charting;

namespace SilverlightApplication
{
    public partial class InCahrt : UserControl
    {
        public InCahrt()
        {
            InitializeComponent();
            //Chart();

            InitializeComponent();
            setChart("温度柱柱状图");
            ConfigureChart();
            //prt.Click += new RoutedEventHandler(prt_Click);
        }

        //private void Chart()
        //{
        //    DataSeries series = new DataSeries();
        //    series.Definition = new HorizontalBarSeriesDefinition();//HorizontalBarSeriesDefinition   BarSeriesDefinition

        //    series.LegendLabel = "温度";

        //    for (int i = 0; i < 8; i++)
        //    {
        //        series.Add(new DataPoint(DateTime.Now.AddDays(i).ToString(), i * i));
        //    }
        //    radChart.DefaultView.ChartArea.DataSeries.Add(series);
        //    radChart.Width = 600;
        //    radChart.Height = 500;
        //}

        //void prt_Click(object sender, RoutedEventArgs e)
        //{
        //    PrintDocument prtDoc = new PrintDocument();
        //    prtDoc.PrintPage += new EventHandler<PrintPageEventArgs>(prtDoc_PrintPage);
        //    prtDoc.Print("温度柱柱状图");

        //}

        //private void prtDoc_PrintPage(object sender, PrintPageEventArgs e)
        //{
        //    e.PageVisual = radChart;

        //}


        private void ConfigureChart()
        {
            LineSeriesDefinition lineSeries = new LineSeriesDefinition();
            lineSeries.ShowItemLabels = false;
            lineSeries.ShowPointMarks = false;

            radChart.DefaultView.ChartArea.ZoomScrollSettingsX.ScrollMode = ScrollMode.ScrollAndZoom;
            radChart.DefaultView.ChartArea.ZoomScrollSettingsY.ScrollMode = ScrollMode.ScrollAndZoom;

            radChart.DefaultView.ChartArea.NoDataString = "正在载入图形数据，请等待...";


            radChart.DefaultView.ChartArea.Padding = new Thickness(5, 10, 20, 5);

            radChart.DefaultView.ChartArea.LabelFormatBehavior = LabelFormatBehavior.None;
            radChart.SamplingSettings.SamplingThreshold = 1000;  //此属性用于控制动画的时间
            radChart.DefaultView.ChartArea.EnableAnimations = true; //此属性控制动画效果
            radChart.DefaultView.ChartArea.EnableTransitionAnimations = true;

            radChart.DefaultView.ChartLegend.Visibility = Visibility.Collapsed;
        }

        private void setChart(string title)
        {
            radChart.DefaultView.ChartTitle.Content = title;
            this.radChart.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.None;
            // this.radChart.DefaultView.ChartLegendPosition = Telerik.Windows.Controls.Dock.Bottom;
            radChart.DefaultView.ChartArea.AxisX.MajorGridLinesVisibility = Visibility.Visible;
            radChart.DefaultView.ChartArea.AxisY.StripLinesVisibility = Visibility.Collapsed;
            radChart.DefaultView.ChartArea.AxisY.MajorGridLinesVisibility = Visibility.Visible;
            radChart.DefaultView.ChartArea.AxisY.MinorGridLinesVisibility = Visibility.Collapsed;
            this.radChart.DefaultView.ChartArea.AxisY.AxisStyles.GridLineStyle = this.Resources["GridLineStyle"] as Style;
            this.radChart.DefaultView.ChartArea.AxisX.AxisStyles.GridLineStyle = this.Resources["GridLineStyle"] as Style;

            radChart.DefaultView.ChartTitle.HorizontalAlignment = HorizontalAlignment.Center;

            radChart.DefaultView.ChartArea.AxisX.AutoRange = true;
            radChart.DefaultView.ChartArea.AxisX.StripLinesVisibility = Visibility.Visible;
            radChart.DefaultView.ChartArea.AxisY.StripLinesVisibility = Visibility.Visible;
            radChart.DefaultView.ChartTitle.HorizontalAlignment = HorizontalAlignment.Center;
            radChart.DefaultView.ChartLegend.Header = "图例";
            radChart.DefaultView.ChartLegend.UseAutoGeneratedItems = true;
            //X轴标题
            radChart.DefaultView.ChartArea.AxisX.Title = "地点";
            radChart.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;
            //Y轴标题
            radChart.DefaultView.ChartArea.AxisY.Title = "温度";
            Data();
        }

        private void Data()
        {
            DataSeries series = new DataSeries();
            series.Definition = new HorizontalBarSeriesDefinition();
            radChart.Width = 600;
            radChart.Height = 300;

            for (int i = 1; i < 8; i++)
            {
                series.Add(new DataPoint(i, i * i));
            }
            radChart.DefaultView.ChartArea.DataSeries.Add(series);
        }
    }
}
